version: '3.9'
services:
  vsporte-auth-server:
    build:
      context: .
    container_name: vsporte-auth-server
    command: [ "./runapp.sh" ]
    ports:
      - "8000:8000"
    env_file:
      - .env
