"""empty message

Revision ID: 45d30985f99c
Revises: ce3aee0ba471
Create Date: 2023-12-13 02:45:11.813065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d30985f99c'
down_revision: Union[str, None] = 'ce3aee0ba471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles_in_services', ['user_id', 'service'])
    op.drop_index('ix_users_email', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_constraint(None, 'roles_in_services', type_='unique')
    # ### end Alembic commands ###
