"""empty message

Revision ID: 8645bc0c040c
Revises: 
Create Date: 2023-12-11 20:33:24.233660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8645bc0c040c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=50), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('password_hash', sa.String(length=300), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('roles_in_services',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('role', sa.Enum('unspecified', 'admin', 'client', name='roles'), nullable=False),
                    sa.Column('service', sa.String(length=50), nullable=False),
                    # manually added ondelete="CASCADE"
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete="CASCADE"),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_roles_in_services_user_id'), 'roles_in_services', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_in_services_user_id'), table_name='roles_in_services')
    op.drop_table('roles_in_services')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
